import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "../components/QueryProvider";
import AuthProvider from "@/components/AuthProvider";
import UserMenu from "@/components/UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-50`}
      >
        <AuthProvider>
          <div className="min-h-screen flex flex-col">
            <header className="sticky top-0 z-50 w-full border-b bg-white/70 backdrop-blur px-6 py-3 flex items-center justify-between">
              <h1 className="text-lg font-semibold">NextJS Todo</h1>
              <UserMenu />
            </header>
            <QueryProvider>
              <div className="flex-1">{children}</div>
            </QueryProvider>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
